-- AlterTable
ALTER TABLE "Balance" ALTER COLUMN "amount" SET DEFAULT 0.0,
ALTER COLUMN "amount" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "locked_amount" SET DEFAULT 0.0,
ALTER COLUMN "locked_amount" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "PollsOption" ADD COLUMN     "dynamic_price" DOUBLE PRECISION NOT NULL DEFAULT 0.5,
ADD COLUMN     "initial_price" DOUBLE PRECISION NOT NULL DEFAULT 0.5,
ADD COLUMN     "total_bets" DOUBLE PRECISION NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "Submissions" ADD COLUMN     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "isWinner" BOOLEAN NOT NULL DEFAULT false;
