-- AlterTable
ALTER TABLE "Balance" ALTER COLUMN "locked_amount" SET DEFAULT 0,
ALTER COLUMN "locked_amount" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "pending_amount" SET DEFAULT 0,
ALTER COLUMN "pending_amount" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "Payout" ALTER COLUMN "amount" SET DEFAULT 0.0,
ALTER COLUMN "amount" SET DATA TYPE DOUBLE PRECISION;
